import Foundation

/// Probe that references symbols generated by the String Catalog compiler
/// (`STRING_CATALOG_GENERATE_SYMBOLS=YES`). The accessors below exist only in
/// the build-time generated file `GeneratedStringSymbols_Localizable.swift`
/// under `DerivedSources`, never in any checked-in source.
@available(macOS 13, *)
enum StringCatProbe {
    /// References the generated static var accessor for the `greeting_hello` key.
    static var greeting: LocalizedStringResource {
        LocalizedStringResource.greetingHello
    }

    /// References the generated static func accessor for the `items_count` key.
    /// The `%lld` format argument makes the generated accessor a function.
    static func itemsSummary(_ count: Int) -> LocalizedStringResource {
        LocalizedStringResource.itemsCount(count)
    }
}
