import Intents

// `GreetingIntent`, its `name` parameter, `GreetingIntentResponse`, and
// `GreetingIntentResponseCode` are generated by intentbuilderc from
// Intents.intentdefinition into
// <DERIVED_FILE_DIR>/IntentDefinitionGenerated/Intents/GreetingIntent.swift —
// they exist ONLY there, never in the project graph. So the editor resolves
// them only if our BSP folds DerivedSources into the per-file inputs.
enum IntentsProbe {
    static let intent: GreetingIntent = {
        let intent = GreetingIntent()
        intent.name = "world"
        return intent
    }()

    static func respond() -> GreetingIntentResponse {
        GreetingIntentResponse(code: .success, userActivity: nil)
    }

    static let code: GreetingIntentResponseCode = .success
}
