import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * SweetPad ships two independent products, so the docs ship two independent
 * sidebars. A reader in the CLI docs never sees the extension tree, and vice
 * versa; the navbar is the only place the two meet.
 */

function heading(label: string) {
  return {
    type: 'html' as const,
    value: `<div class="sidebarHeading">${label}</div>`,
    defaultStyle: false,
  };
}

/** A group label inside one product's sidebar, quieter than the product heading. */
function group(label: string) {
  return {
    type: 'html' as const,
    value: `<div class="sidebarGroup">${label}</div>`,
    defaultStyle: false,
  };
}

const contributing = {
  type: 'category' as const,
  label: 'Contributing',
  collapsed: true,
  items: [{ type: 'autogenerated' as const, dirName: 'contributing' }],
};

const sidebars: SidebarsConfig = {
  // Listed explicitly rather than autogenerated, so the guides can be grouped
  // without pushing the product name into the URL. A new page needs a line here.
  cliSidebar: [
    heading('SweetPad CLI'),
    'cli/getting-started',
    'cli/overview',
    group('Daily loop'),
    'cli/build-and-run',
    'cli/testing',
    'cli/formatting',
    'cli/hot-reload',
    group('Where it runs'),
    'cli/destinations',
    'cli/simulators',
    'cli/app-lifecycle',
    group('Your project'),
    'cli/project-new',
    'cli/project',
    'cli/generated-projects',
    'cli/archive',
    'cli/merge',
    group('Setup'),
    'cli/configuration',
    'cli/autocomplete',
    group('Automation'),
    'cli/scripts-and-ci',
    'cli/agent-skills',
    'cli/agent-cli',
    group('Reference'),
    'cli/troubleshooting',
    'cli/reference',
    { type: 'html', value: '<div class="sidebarDivider"></div>', defaultStyle: false },
    'intro',
    contributing,
  ],

  // Listed by hand for the same reason as the CLI tree above: the groups are
  // what keep an 18-page sidebar scannable. A new page needs a line here.
  vscodeSidebar: [
    heading('VS Code extension'),
    'vscode/getting-started',
    'vscode/overview',
    group('Features'),
    'vscode/build',
    'vscode/debug',
    'vscode/tests',
    'vscode/format',
    'vscode/autocomplete',
    'vscode/hot-reload',
    group('Where it runs'),
    'vscode/destinations',
    'vscode/simulators',
    'vscode/devices',
    group('Your project'),
    'vscode/tuist',
    'vscode/xcodegen',
    'vscode/worktree',
    group('Setup'),
    'vscode/tools',
    'vscode/settings',
    group('Reference'),
    'vscode/commands',
    'vscode/troubleshooting',
    { type: 'html', value: '<div class="sidebarDivider"></div>', defaultStyle: false },
    'intro',
    contributing,
  ],
};

export default sidebars;
