//! Serialized [`Catalog`] cache — embed a baked catalog in the binary and
//! cache parsed ones on disk.
//!
//! Parsing Apple's xcspecs is ~32 ms per process (hundreds of OpenStep-plist
//! files); the resulting [`Catalog`] is plain data (~300 KB serialized for the
//! latest Xcode). This module freezes a `Catalog` to a compact, dependency-free
//! binary blob so subsequent runs skip the walk + parse entirely:
//!
//! * [`embedded`] returns the catalog baked into the binary at build time
//!   (`catalog_embedded.bin`, regenerated by `examples/gen_embedded_catalog.rs`).
//!   This is what powers `build-settings` when no `--xcspec-root` is passed.
//! * [`load_cached_or_build`] is the `--xcspec-root` path: it reads a cache file
//!   if one exists and is still valid for that root (validated by a cheap
//!   stat-based fingerprint), otherwise parses via [`xcspec::load_catalog`],
//!   writes the cache, and returns the result.
//!
//! ## Wire format (little-endian)
//!
//! ```text
//! magic        "SPC1"   (4 bytes)
//! format_ver   u8       (bump on any layout change below — invalidates old blobs)
//! fingerprint  u64      (source fingerprint; 0 for the embedded blob)
//! <catalog body>
//! ```
//!
//! Strings are `u32` length + UTF-8 bytes; `Option<String>` is a `u8` tag then
//! the string when present; sequences/maps are a `u32` count then their items.

use std::collections::{BTreeMap, BTreeSet};
use std::collections::HashMap;
use std::ffi::OsStr;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{LazyLock, Mutex, MutexGuard, PoisonError};
use std::time::UNIX_EPOCH;

use crate::xcconfig::{Assignment, Condition};
use crate::xcspec::{self, Catalog, CliArgs, CompilerOption, ProductTypeDefaults};

const MAGIC: &[u8; 4] = b"SPC1";
/// Bump whenever the serialized layout (or the [`Catalog`] shape) changes, so a
/// sweetpad upgrade transparently rebuilds disk caches and the embedded blob is
/// rejected if stale.
const FORMAT_VERSION: u8 = 5;

#[derive(Debug)]
pub enum Error {
    Io(io::Error),
    /// The blob's header or body didn't match what we expect (truncated,
    /// wrong magic, or an incompatible `FORMAT_VERSION`).
    Corrupt(&'static str),
    /// Falling back to a live parse failed.
    Build(xcspec::Error),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Io(e) => write!(f, "catalog cache io: {e}"),
            Error::Corrupt(why) => write!(f, "catalog cache corrupt: {why}"),
            Error::Build(e) => write!(f, "catalog build: {e}"),
        }
    }
}

impl std::error::Error for Error {}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Error::Io(e)
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Serialize a catalog to the wire format, tagging it with `fingerprint`
/// (use `0` for a build-time embed that isn't tied to an on-disk source).
#[must_use]
pub fn serialize(catalog: &Catalog, fingerprint: u64) -> Vec<u8> {
    let mut out = Vec::with_capacity(1 << 18);
    out.extend_from_slice(MAGIC);
    out.push(FORMAT_VERSION);
    write_u64(&mut out, fingerprint);
    write_catalog(&mut out, catalog);
    out
}

/// Deserialize a catalog, returning it alongside the fingerprint it was tagged
/// with. Validates magic + format version.
pub fn deserialize(bytes: &[u8]) -> Result<(Catalog, u64), Error> {
    let mut r = Reader::new(bytes);
    if r.take(4)? != MAGIC {
        return Err(Error::Corrupt("bad magic"));
    }
    if r.u8()? != FORMAT_VERSION {
        return Err(Error::Corrupt("format version mismatch"));
    }
    let fingerprint = r.u64()?;
    let catalog = read_catalog(&mut r)?;
    Ok((catalog, fingerprint))
}

/// The catalog baked into the binary (latest captured Xcode). Used as the
/// default defaults-layer when no `--xcspec-root` is supplied.
pub fn embedded() -> Result<Catalog, Error> {
    static EMBEDDED: &[u8] = include_bytes!("catalog_embedded.bin");
    deserialize(EMBEDDED).map(|(catalog, _)| catalog)
}

/// Load the catalog for `xcspec_root`, using a serialized cache when one exists
/// and is still valid, otherwise parsing the specs and writing the cache.
///
/// `cache_override` pins the cache file path; when `None` a path under the OS
/// cache dir, keyed by `xcspec_root`, is used. Cache writes are best-effort — a
/// failure to persist never fails the call.
pub fn load_cached_or_build(
    xcspec_root: &Path,
    sdksettings_root: Option<&Path>,
    cache_override: Option<&Path>,
) -> Result<Catalog, Error> {
    let fingerprint = source_fingerprint(xcspec_root, sdksettings_root);
    load_with_fingerprint(xcspec_root, sdksettings_root, cache_override, fingerprint)
}

/// Like [`load_cached_or_build`], but validate the cache against an explicit
/// `key` (e.g. an Xcode build version) rather than a stat-based fingerprint.
/// Cheaper and more robust when the caller already knows the source identity —
/// the specs are a pure function of which Xcode they came from.
pub fn load_cached_or_build_keyed(
    xcspec_root: &Path,
    sdksettings_root: Option<&Path>,
    cache_override: Option<&Path>,
    key: &str,
) -> Result<Catalog, Error> {
    let fingerprint = fnv1a(key.as_bytes(), FNV_OFFSET);
    load_with_fingerprint(xcspec_root, sdksettings_root, cache_override, fingerprint)
}

/// Process-global cache of parsed catalogs, keyed by the same fingerprint the
/// disk cache uses. The node addon is long-lived, so once a catalog is parsed
/// (or read from disk) it stays in memory for the rest of the session and every
/// later `build-settings` call skips the cache-file read + deserialize.
static MEMORY_CACHE: LazyLock<Mutex<HashMap<u64, Catalog>>> =
    LazyLock::new(|| Mutex::new(HashMap::new()));

fn memory_cache() -> MutexGuard<'static, HashMap<u64, Catalog>> {
    MEMORY_CACHE.lock().unwrap_or_else(PoisonError::into_inner)
}

fn load_with_fingerprint(
    xcspec_root: &Path,
    sdksettings_root: Option<&Path>,
    cache_override: Option<&Path>,
    fingerprint: u64,
) -> Result<Catalog, Error> {
    // In-memory tier: reuse a catalog already parsed/read in this process.
    {
        let cache = memory_cache();
        if let Some(catalog) = cache.get(&fingerprint) {
            return Ok(catalog.clone());
        }
    }

    let cache_path =
        cache_override.map_or_else(|| default_cache_path(xcspec_root), Path::to_path_buf);

    let catalog = if let Some(catalog) = read_valid_cache(&cache_path, fingerprint) {
        catalog
    } else {
        let catalog = xcspec::load_catalog(xcspec_root, sdksettings_root).map_err(Error::Build)?;
        let _ = write_cache(&cache_path, &serialize(&catalog, fingerprint));
        catalog
    };

    memory_cache().insert(fingerprint, catalog.clone());
    Ok(catalog)
}

/// Read `path` and return its catalog only if it deserializes cleanly and its
/// stored fingerprint matches `fingerprint`. Any miss → `None` (rebuild).
fn read_valid_cache(path: &Path, fingerprint: u64) -> Option<Catalog> {
    let bytes = fs::read(path).ok()?;
    let (catalog, stored) = deserialize(&bytes).ok()?;
    (stored == fingerprint).then_some(catalog)
}

// ---------------------------------------------------------------------------
// Cache file placement + validation
// ---------------------------------------------------------------------------

/// Default cache file for a given xcspec root: `<cache-dir>/sweetpad/catalog-<hash>.bin`,
/// where the hash is derived from the root's canonical path so distinct roots
/// (e.g. different Xcodes) don't collide.
fn default_cache_path(xcspec_root: &Path) -> PathBuf {
    let canonical = fs::canonicalize(xcspec_root).unwrap_or_else(|_| xcspec_root.to_path_buf());
    let key = fnv1a(canonical.to_string_lossy().as_bytes(), FNV_OFFSET);
    cache_dir()
        .join("sweetpad")
        .join(format!("catalog-{key:016x}.bin"))
}

/// Base cache directory: `$SWEETPAD_CACHE_DIR`, else `$XDG_CACHE_HOME`, else
/// `$HOME/.cache`, else the platform temp dir.
fn cache_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("SWEETPAD_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    if let Some(dir) = std::env::var_os("XDG_CACHE_HOME") {
        return PathBuf::from(dir);
    }
    if let Some(home) = std::env::var_os("HOME") {
        return PathBuf::from(home).join(".cache");
    }
    std::env::temp_dir()
}

fn write_cache(path: &Path, bytes: &[u8]) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, bytes)
}

/// Cheap fingerprint of the spec sources: an FNV-1a hash over the sorted set of
/// `(path, len, mtime)` for every `*.xcspec` and `SDKSettings.plist` under the
/// roots. Stat-only — it never reads file *contents* (that's the parse cost
/// we're avoiding), so a mismatch means "specs changed → rebuild."
fn source_fingerprint(xcspec_root: &Path, sdksettings_root: Option<&Path>) -> u64 {
    let mut entries: BTreeSet<(String, u64, u128)> = BTreeSet::new();
    collect_stats(
        xcspec_root,
        &|p| p.extension() == Some(OsStr::new("xcspec")),
        &mut entries,
    );
    if let Some(root) = sdksettings_root {
        collect_stats(
            root,
            &|p| p.file_name() == Some(OsStr::new("SDKSettings.plist")),
            &mut entries,
        );
    }
    let mut h = FNV_OFFSET;
    for (path, len, mtime) in &entries {
        h = fnv1a(path.as_bytes(), h);
        h = fnv1a(&len.to_le_bytes(), h);
        h = fnv1a(&mtime.to_le_bytes(), h);
    }
    h
}

fn collect_stats(
    dir: &Path,
    keep: &dyn Fn(&Path) -> bool,
    out: &mut BTreeSet<(String, u64, u128)>,
) {
    let Ok(rd) = fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_stats(&path, keep, out);
        } else if keep(&path) {
            let meta = entry.metadata().ok();
            let len = meta.as_ref().map_or(0, fs::Metadata::len);
            let mtime = meta
                .and_then(|m| m.modified().ok())
                .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
                .map_or(0, |d| d.as_nanos());
            out.insert((path.to_string_lossy().into_owned(), len, mtime));
        }
    }
}

const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

fn fnv1a(bytes: &[u8], mut hash: u64) -> u64 {
    for &b in bytes {
        hash ^= u64::from(b);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

// ---------------------------------------------------------------------------
// Catalog <-> bytes
// ---------------------------------------------------------------------------

fn write_catalog(out: &mut Vec<u8>, c: &Catalog) {
    write_opt_str(out, c.xcode_version.as_deref());
    write_opt_str(out, c.developer_dir.as_deref());
    write_assignments(out, &c.universal);
    write_str_map(out, &c.domain_specific, |out, v| write_assignments(out, v));
    write_str_map(out, &c.sdks, |out, v| write_assignments(out, v));
    write_str_map(out, &c.product_types, write_product_type);
    write_str_map(out, &c.sdk_paths, |out, p| {
        write_str(out, &p.to_string_lossy());
    });
    write_str_map(out, &c.compiler_options, |out, v| {
        write_compiler_options(out, v);
    });
}

fn read_catalog(r: &mut Reader) -> Result<Catalog, Error> {
    Ok(Catalog {
        xcode_version: r.opt_str()?,
        developer_dir: r.opt_str()?,
        universal: read_assignments(r)?,
        domain_specific: read_str_map(r, read_assignments)?,
        sdks: read_str_map(r, read_assignments)?,
        product_types: read_str_map(r, read_product_type)?,
        sdk_paths: read_str_map(r, |r| Ok(PathBuf::from(r.str()?)))?,
        compiler_options: read_str_map(r, read_compiler_options)?,
    })
}

fn write_compiler_options(out: &mut Vec<u8>, opts: &[CompilerOption]) {
    write_len(out, opts.len());
    for o in opts {
        write_str(out, &o.name);
        out.push(u8::from(o.is_list));
        write_opt_str(out, o.flag.as_deref());
        write_opt_str(out, o.prefix_flag.as_deref());
        match &o.args {
            None => out.push(0),
            Some(CliArgs::List(v)) => {
                out.push(1);
                write_str_list(out, v);
            }
            Some(CliArgs::ByValue { map, otherwise }) => {
                out.push(2);
                write_str_map(out, map, |out, v| write_str_list(out, v));
                match otherwise {
                    None => out.push(0),
                    Some(v) => {
                        out.push(1);
                        write_str_list(out, v);
                    }
                }
            }
        }
        write_str_list(out, &o.file_types);
        write_str_list(out, &o.architectures);
        write_opt_str(out, o.condition.as_deref());
    }
}

fn read_compiler_options(r: &mut Reader) -> Result<Vec<CompilerOption>, Error> {
    let n = r.u32()? as usize;
    let mut v = Vec::with_capacity(n.min(1 << 14));
    for _ in 0..n {
        let name = r.str()?;
        let is_list = r.u8()? != 0;
        let flag = r.opt_str()?;
        let prefix_flag = r.opt_str()?;
        let args = match r.u8()? {
            0 => None,
            1 => Some(CliArgs::List(read_str_list(r)?)),
            2 => {
                let map = read_str_map(r, read_str_list)?;
                let otherwise = if r.u8()? != 0 {
                    Some(read_str_list(r)?)
                } else {
                    None
                };
                Some(CliArgs::ByValue { map, otherwise })
            }
            _ => return Err(Error::Corrupt("bad CliArgs tag")),
        };
        let file_types = read_str_list(r)?;
        let architectures = read_str_list(r)?;
        let condition = r.opt_str()?;
        v.push(CompilerOption {
            name,
            is_list,
            flag,
            prefix_flag,
            args,
            file_types,
            architectures,
            condition,
        });
    }
    Ok(v)
}

fn write_str_list(out: &mut Vec<u8>, items: &[String]) {
    write_len(out, items.len());
    for s in items {
        write_str(out, s);
    }
}

fn read_str_list(r: &mut Reader) -> Result<Vec<String>, Error> {
    let n = r.u32()? as usize;
    let mut v = Vec::with_capacity(n.min(1 << 12));
    for _ in 0..n {
        v.push(r.str()?);
    }
    Ok(v)
}

fn write_product_type(out: &mut Vec<u8>, pt: &ProductTypeDefaults) {
    write_opt_str(out, pt.based_on.as_deref());
    write_opt_str(out, pt.package_type.as_deref());
    write_assignments(out, &pt.defaults);
}

fn read_product_type(r: &mut Reader) -> Result<ProductTypeDefaults, Error> {
    Ok(ProductTypeDefaults {
        based_on: r.opt_str()?,
        package_type: r.opt_str()?,
        defaults: read_assignments(r)?,
    })
}

fn write_assignments(out: &mut Vec<u8>, items: &[Assignment]) {
    write_len(out, items.len());
    for a in items {
        write_str(out, &a.key);
        write_str(out, &a.value);
        write_opt_str(out, a.condition.as_deref());
        write_len(out, a.conditions.len());
        for c in &a.conditions {
            write_str(out, &c.key);
            write_str(out, &c.value);
        }
    }
}

fn read_assignments(r: &mut Reader) -> Result<Vec<Assignment>, Error> {
    let n = r.u32()? as usize;
    let mut v = Vec::with_capacity(n.min(1 << 16));
    for _ in 0..n {
        let key = r.str()?;
        let value = r.str()?;
        let condition = r.opt_str()?;
        let cn = r.u32()? as usize;
        let mut conditions = Vec::with_capacity(cn.min(1 << 8));
        for _ in 0..cn {
            conditions.push(Condition {
                key: r.str()?,
                value: r.str()?,
            });
        }
        v.push(Assignment {
            key,
            conditions,
            value,
            condition,
        });
    }
    Ok(v)
}

fn write_str_map<V>(
    out: &mut Vec<u8>,
    map: &BTreeMap<String, V>,
    mut write_v: impl FnMut(&mut Vec<u8>, &V),
) {
    write_len(out, map.len());
    for (k, v) in map {
        write_str(out, k);
        write_v(out, v);
    }
}

fn read_str_map<V>(
    r: &mut Reader,
    mut read_v: impl FnMut(&mut Reader) -> Result<V, Error>,
) -> Result<BTreeMap<String, V>, Error> {
    let n = r.u32()? as usize;
    let mut map = BTreeMap::new();
    for _ in 0..n {
        let k = r.str()?;
        let v = read_v(r)?;
        map.insert(k, v);
    }
    Ok(map)
}

// ---------------------------------------------------------------------------
// Low-level encode/decode
// ---------------------------------------------------------------------------

fn write_u32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_le_bytes());
}

/// Write a collection length as a `u32`. Catalog fields are orders of magnitude
/// below `u32::MAX`; a length that large is a corrupt in-memory catalog.
fn write_len(out: &mut Vec<u8>, len: usize) {
    write_u32(
        out,
        u32::try_from(len).expect("catalog field length exceeds u32"),
    );
}

fn write_u64(out: &mut Vec<u8>, v: u64) {
    out.extend_from_slice(&v.to_le_bytes());
}

fn write_str(out: &mut Vec<u8>, s: &str) {
    write_len(out, s.len());
    out.extend_from_slice(s.as_bytes());
}

fn write_opt_str(out: &mut Vec<u8>, s: Option<&str>) {
    match s {
        Some(s) => {
            out.push(1);
            write_str(out, s);
        }
        None => out.push(0),
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(buf: &'a [u8]) -> Self {
        Reader { buf, pos: 0 }
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
        let end = self
            .pos
            .checked_add(n)
            .ok_or(Error::Corrupt("length overflow"))?;
        let slice = self
            .buf
            .get(self.pos..end)
            .ok_or(Error::Corrupt("unexpected eof"))?;
        self.pos = end;
        Ok(slice)
    }

    fn u8(&mut self) -> Result<u8, Error> {
        Ok(self.take(1)?[0])
    }

    fn u32(&mut self) -> Result<u32, Error> {
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }

    fn u64(&mut self) -> Result<u64, Error> {
        let b = self.take(8)?;
        Ok(u64::from_le_bytes(b.try_into().unwrap()))
    }

    fn str(&mut self) -> Result<String, Error> {
        let n = self.u32()? as usize;
        let bytes = self.take(n)?;
        String::from_utf8(bytes.to_vec()).map_err(|_| Error::Corrupt("invalid utf-8"))
    }

    fn opt_str(&mut self) -> Result<Option<String>, Error> {
        match self.u8()? {
            0 => Ok(None),
            1 => Ok(Some(self.str()?)),
            _ => Err(Error::Corrupt("bad option tag")),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn asg(key: &str, value: &str) -> Assignment {
        Assignment {
            key: key.into(),
            conditions: Vec::new(),
            value: value.into(),
            condition: None,
        }
    }

    fn sample() -> Catalog {
        let mut c = Catalog {
            universal: vec![asg("ALWAYS_SEARCH_USER_PATHS", "NO")],
            xcode_version: Some("26.5.0".into()),
            developer_dir: Some("/Applications/Xcode.app/Contents/Developer".into()),
            ..Catalog::default()
        };
        c.universal.push(Assignment {
            key: "GCC_C_LANGUAGE_STANDARD".into(),
            conditions: vec![Condition {
                key: "sdk".into(),
                value: "macosx*".into(),
            }],
            value: "gnu17".into(),
            condition: Some("$(SOMETHING) == YES".into()),
        });
        c.domain_specific
            .insert("macosx".into(), vec![asg("BUNDLE_FORMAT", "deep")]);
        c.sdks.insert(
            "macosx".into(),
            vec![asg("MACOSX_DEPLOYMENT_TARGET", "26.0")],
        );
        c.product_types.insert(
            "com.apple.product-type.application".into(),
            ProductTypeDefaults {
                based_on: Some("com.apple.product-type.bundle".into()),
                package_type: Some("com.apple.package-type.wrapper".into()),
                defaults: vec![asg("WRAPPER_EXTENSION", "app")],
            },
        );
        c.sdk_paths.insert(
            "macosx".into(),
            PathBuf::from("/Applications/Xcode.app/Contents/.../MacOSX26.0.sdk"),
        );
        c.compiler_options.insert(
            "com.apple.xcode.tools.swift.compiler".into(),
            vec![
                CompilerOption {
                    name: "SWIFT_OPTIMIZATION_LEVEL".into(),
                    is_list: false,
                    flag: None,
                    prefix_flag: None,
                    args: Some(CliArgs::ByValue {
                        map: BTreeMap::from([(
                            "-Owholemodule".into(),
                            vec!["-O".into(), "-whole-module-optimization".into()],
                        )]),
                        otherwise: Some(vec!["$(value)".into()]),
                    }),
                    file_types: vec![],
                    architectures: vec![],
                    condition: None,
                },
                CompilerOption {
                    name: "SWIFT_ACTIVE_COMPILATION_CONDITIONS".into(),
                    is_list: true,
                    flag: None,
                    prefix_flag: None,
                    args: Some(CliArgs::List(vec!["-D$(value)".into()])),
                    file_types: vec!["sourcecode.c.objc".into(), "sourcecode.cpp.objcpp".into()],
                    architectures: vec!["x86_64".into()],
                    condition: Some("$(CLANG_ENABLE_MODULES)".into()),
                },
                CompilerOption {
                    name: "SWIFT_OBJC_BRIDGING_HEADER".into(),
                    is_list: false,
                    flag: Some("-import-objc-header".into()),
                    prefix_flag: None,
                    args: None,
                    file_types: vec![],
                    architectures: vec![],
                    condition: None,
                },
            ],
        );
        c
    }

    fn assert_same(a: &Catalog, b: &Catalog) {
        assert_eq!(a.xcode_version, b.xcode_version);
        assert_eq!(a.developer_dir, b.developer_dir);
        assert_eq!(a.universal, b.universal);
        assert_eq!(a.domain_specific, b.domain_specific);
        assert_eq!(a.sdks, b.sdks);
        assert_eq!(a.sdk_paths, b.sdk_paths);
        assert_eq!(a.compiler_options, b.compiler_options);
        assert_eq!(a.product_types.len(), b.product_types.len());
        for (k, av) in &a.product_types {
            let bv = b.product_types.get(k).expect("missing product type");
            assert_eq!(av.based_on, bv.based_on);
            assert_eq!(av.package_type, bv.package_type);
            assert_eq!(av.defaults, bv.defaults);
        }
    }

    #[test]
    fn round_trips() {
        let original = sample();
        let bytes = serialize(&original, 0xdead_beef);
        let (decoded, fp) = deserialize(&bytes).expect("deserialize");
        assert_eq!(fp, 0xdead_beef);
        assert_same(&original, &decoded);
    }

    #[test]
    fn round_trips_empty() {
        let original = Catalog::default();
        let bytes = serialize(&original, 0);
        let (decoded, fp) = deserialize(&bytes).expect("deserialize");
        assert_eq!(fp, 0);
        assert_same(&original, &decoded);
    }

    #[test]
    fn rejects_bad_magic() {
        let mut bytes = serialize(&sample(), 0);
        bytes[0] = b'X';
        assert!(matches!(deserialize(&bytes), Err(Error::Corrupt(_))));
    }

    #[test]
    fn rejects_truncated() {
        let bytes = serialize(&sample(), 0);
        assert!(matches!(
            deserialize(&bytes[..bytes.len() - 4]),
            Err(Error::Corrupt(_))
        ));
    }

    #[test]
    fn rejects_wrong_format_version() {
        let mut bytes = serialize(&sample(), 0);
        bytes[4] = FORMAT_VERSION.wrapping_add(1);
        assert!(matches!(deserialize(&bytes), Err(Error::Corrupt(_))));
    }
}
