import SwiftUI

// These symbols are generated by actool into
// <DERIVED_FILE_DIR>/GeneratedAssetSymbols.swift and exist ONLY there.
// Note actool's naming rule: a color named "BrandColor" loses its trailing
// "Color" -> .brand, but an image "StarIcon" keeps its suffix -> .starIcon.
enum AssetSymProbe {
    static let brandColor: ColorResource = .brand
    static let starIconImage: ImageResource = .starIcon

    static var swatch: some View {
        Color(.brand)
    }

    static var icon: some View {
        Image(.starIcon)
    }
}
