//! The **xtool** backend: a config-generating backend that turns the Xcode
//! project into a SwiftPM package + `xtool.yml`, then builds it with
//! `xtool dev build` — the Linux/Windows build story. See
//! `docs/dev/build-backends.md` and `docs/dev/xtool-linux-build.md`.
//!
//! `generate` consumes the normalized [`BuildPlan`](crate::cli::plan::BuildPlan):
//! app identity → `xtool.yml`, the source graph → a `Package.swift` whose
//! `.library` target lists the project's sources (xtool bundles the library into
//! an iOS app). `build` runs `xtool dev build` against the committed config.
//!
//! The rendered `Package.swift` follows xtool's documented app template
//! (swift-tools-version 6.0, a `.library` product, no external dependency). It is
//! a best-effort reconstruction and is exercised end-to-end by the
//! `xtool-linux-build` CI workflow; treat that as the source of truth.

use std::fs;
use std::path::{Path, PathBuf};

use crate::cli::backend::{BuildBackend, BuildOptions};
use crate::cli::plan::{self, BuildPlan};
use crate::cli::resolve::{Container, Resolved};
use crate::cli::{CliError, CliResult, Context, process};

pub struct XtoolBackend;

impl BuildBackend for XtoolBackend {
    fn id(&self) -> &'static str {
        "xtool"
    }

    fn can_build(&self, _container: &Container) -> bool {
        // Never auto-selected: xtool builds a generated package, so it is only
        // used when explicitly requested with `--backend xtool`.
        false
    }

    fn build(&self, ctx: &mut Context, resolved: &Resolved, _opts: &BuildOptions) -> CliResult {
        let dir = package_dir(&resolved.container);
        if !dir.join("xtool.yml").exists() {
            return Err(CliError::new(
                "no xtool.yml found — run `sweetpad build generate --backend xtool` first",
            ));
        }
        ctx.out.note("building with `xtool dev build`");
        process::stream("xtool", &["dev", "build"], Some(&dir))
    }

    fn generate(&self, ctx: &mut Context, resolved: &Resolved, out_dir: &Path) -> CliResult {
        let plan = plan::build_plan(ctx, resolved)?;
        fs::create_dir_all(out_dir)
            .map_err(|e| CliError::new(format!("creating {}: {e}", out_dir.display())))?;

        for (path, contents) in render(&plan, out_dir)? {
            fs::write(&path, contents)
                .map_err(|e| CliError::new(format!("writing {}: {e}", path.display())))?;
            ctx.out.note(&format!("wrote {}", path.display()));
        }
        ctx.out.note(&format!(
            "generated xtool config for {} — build with `sweetpad build start --backend xtool`",
            plan.product_name
        ));
        Ok(())
    }
}

/// The directory an xtool package lives/builds in: the directory containing the
/// project container (matches `build generate`'s default output).
fn package_dir(container: &Container) -> PathBuf {
    container
        .path()
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

/// The files xtool needs, as `(absolute path, contents)` under `out_dir`.
fn render(plan: &BuildPlan, out_dir: &Path) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![
        (
            out_dir.join("Package.swift"),
            render_package_swift(plan, out_dir)?,
        ),
        (out_dir.join("xtool.yml"), render_xtool_yml(plan)),
    ])
}

/// Render `xtool.yml`. The minimal valid file is `version: 1` + `bundleID`.
fn render_xtool_yml(plan: &BuildPlan) -> String {
    format!(
        "# Generated by sweetpad (build generate --backend xtool). Edit as needed.\n\
         version: 1\n\
         bundleID: {}\n",
        plan.bundle_id
    )
}

/// Render a `Package.swift` whose `.library` target lists the app's sources.
fn render_package_swift(plan: &BuildPlan, out_dir: &Path) -> Result<String, CliError> {
    let name = swift_identifier(&plan.product_name);
    let platform = ios_platform(plan.deployment_target.as_deref());
    let (target_path, sources) = relative_sources(&plan.sources, out_dir)?;

    let source_list = sources
        .iter()
        .map(|s| format!("                \"{s}\","))
        .collect::<Vec<_>>()
        .join("\n");

    Ok(format!(
        "// swift-tools-version: 6.0\n\
         // Generated by sweetpad (build generate --backend xtool). Edit as needed.\n\
         import PackageDescription\n\
         \n\
         let package = Package(\n\
         \x20   name: \"{name}\",\n\
         \x20   platforms: [\n\
         \x20       {platform},\n\
         \x20   ],\n\
         \x20   products: [\n\
         \x20       .library(name: \"{name}\", targets: [\"{name}\"]),\n\
         \x20   ],\n\
         \x20   targets: [\n\
         \x20       .target(\n\
         \x20           name: \"{name}\",\n\
         \x20           path: \"{target_path}\",\n\
         \x20           sources: [\n\
         {source_list}\n\
         \x20           ]\n\
         \x20       ),\n\
         \x20   ]\n\
         )\n"
    ))
}

/// Map an `IPHONEOS_DEPLOYMENT_TARGET` (e.g. `"16.4"`) to a SwiftPM platform
/// (`.iOS(.v16)`), using the major version. Defaults to `.v13` when unknown.
fn ios_platform(deployment_target: Option<&str>) -> String {
    let major = deployment_target
        .and_then(|d| d.split('.').next())
        .and_then(|m| m.parse::<u32>().ok())
        .unwrap_or(13);
    format!(".iOS(.v{major})")
}

/// Sanitize a product name into a valid Swift package/target identifier.
fn swift_identifier(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if cleaned.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("_{cleaned}")
    } else if cleaned.is_empty() {
        "App".to_string()
    } else {
        cleaned
    }
}

/// Compute a SwiftPM target `path` + `sources` list from absolute source paths:
/// the common ancestor directory (relative to the package root `out_dir`) and
/// each file relative to it. Errors if the sources live outside `out_dir`, which
/// SwiftPM can't express.
fn relative_sources(
    sources: &[PathBuf],
    out_dir: &Path,
) -> Result<(String, Vec<String>), CliError> {
    if sources.is_empty() {
        return Err(CliError::new(
            "the app target has no source files to package",
        ));
    }
    let root = canonical(out_dir)?;
    let abs: Vec<PathBuf> = sources
        .iter()
        .map(|s| canonical(s))
        .collect::<Result<_, _>>()?;

    let common = common_ancestor(&abs)
        .ok_or_else(|| CliError::new("the app's sources share no common directory"))?;
    let rel_path = common.strip_prefix(&root).map_err(|_| {
        CliError::new(format!(
            "the app's sources live outside the output directory {}; \
             pass --output to a directory that contains them",
            root.display()
        ))
    })?;
    let target_path = if rel_path.as_os_str().is_empty() {
        ".".to_string()
    } else {
        rel_path.to_string_lossy().into_owned()
    };

    let mut files: Vec<String> = abs
        .iter()
        .map(|s| {
            s.strip_prefix(&common)
                .expect("source under common ancestor")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    files.sort();
    Ok((target_path, files))
}

/// Canonicalize a path, mapping IO errors to a [`CliError`].
fn canonical(p: &Path) -> Result<PathBuf, CliError> {
    fs::canonicalize(p).map_err(|e| CliError::new(format!("resolving {}: {e}", p.display())))
}

/// The deepest directory that is an ancestor of every path's parent.
fn common_ancestor(paths: &[PathBuf]) -> Option<PathBuf> {
    let mut common = paths.first()?.parent()?.to_path_buf();
    for p in paths {
        let dir = p.parent()?;
        while !dir.starts_with(&common) {
            common = common.parent()?.to_path_buf();
        }
    }
    Some(common)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(rel: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join(rel)
    }

    fn strcat_plan() -> (BuildPlan, PathBuf) {
        let dir = fixture("_synthetic-strcat/project");
        let plan = BuildPlan {
            scheme: "StringCatGen".into(),
            configuration: "Debug".into(),
            app_target: "StringCatGen".into(),
            product_name: "StringCatGen".into(),
            bundle_id: "dev.sweetpad.fixture.StringCatGen".into(),
            deployment_target: Some("16.4".into()),
            supported_platforms: None,
            sources: vec![
                dir.join("Sources/App.swift"),
                dir.join("Sources/StringCatProbe.swift"),
            ],
            dependencies: vec![],
        };
        (plan, dir)
    }

    #[test]
    fn xtool_yml_is_minimal_and_carries_the_bundle_id() {
        let (plan, _) = strcat_plan();
        let yml = render_xtool_yml(&plan);
        assert!(yml.contains("version: 1"));
        assert!(yml.contains("bundleID: dev.sweetpad.fixture.StringCatGen"));
    }

    #[test]
    fn package_swift_lists_the_library_target_and_sources() {
        let (plan, dir) = strcat_plan();
        let pkg = render_package_swift(&plan, &dir).expect("render");
        assert!(pkg.contains("swift-tools-version: 6.0"));
        assert!(pkg.contains(".library(name: \"StringCatGen\", targets: [\"StringCatGen\"])"));
        assert!(pkg.contains(".iOS(.v16)"));
        // Sources share the Sources/ directory, so it becomes the target path.
        assert!(pkg.contains("path: \"Sources\""));
        assert!(pkg.contains("\"App.swift\""));
        assert!(pkg.contains("\"StringCatProbe.swift\""));
    }

    #[test]
    fn ios_platform_uses_the_major_version() {
        assert_eq!(ios_platform(Some("16.4")), ".iOS(.v16)");
        assert_eq!(ios_platform(Some("17")), ".iOS(.v17)");
        assert_eq!(ios_platform(None), ".iOS(.v13)");
    }

    #[test]
    fn swift_identifier_sanitizes_names() {
        assert_eq!(swift_identifier("My App"), "My_App");
        assert_eq!(swift_identifier("123App"), "_123App");
        assert_eq!(swift_identifier("Clean"), "Clean");
    }
}
