# This file is generated by PackageBot. Do not edit it directly.

load("//Apps/Consumer:cx_module.bzl", "cx_module")

cx_module(
    features = [
        "swift.upcoming.BareSlashRegexLiterals",
        "swift.upcoming.ForwardTrailingClosures",
        "swift.upcoming.DeprecateApplicationMain",
        "swift.upcoming.NonfrozenEnumExhaustivity",
    ]
)
