// Vscode-free module holding the Swift bootstrap SweetPad scaffolds into a
// user's project, plus the env-var names the extension and the bootstrap agree
// on. Kept separate from `host.ts` (which imports `vscode`) so it can be
// imported by the emit script and unit-tested in isolation.

/** Environment variable carrying the requested preview id (`path:line`). */
export const ENV_PREVIEW_ID = "SWEETPAD_PREVIEW_ID";
/** Environment variable carrying the appearance override (`light`/`dark`). */
export const ENV_PREVIEW_APPEARANCE = "SWEETPAD_PREVIEW_APPEARANCE";

/**
 * The Swift bootstrap dropped into the user's project by `scaffold()`. It is a
 * single, dependency-free file: it discovers `#Preview` macros at runtime by
 * walking the Mach-O `__swift5_proto` section (the discovery validated in
 * `examples/preview-bridge`, adapted from EmergeTools/SnapshotPreviews, MIT),
 * matches the one named by `SWEETPAD_PREVIEW_ID` (by file name + line) and
 * renders exactly that view.
 *
 * Authored with `String.raw` so Swift backslashes (`\.keyPath`, `\(interp)`)
 * survive into the emitted file verbatim while `${ENV_*}` still interpolate.
 * `scripts/emit-preview-host.mjs` writes it to a committed `.swift` file that
 * CI compiles against the real toolchain; a unit test guards against drift.
 */
export const PREVIEW_HOST_BOOTSTRAP = String.raw`// SweetPadPreviewHost.swift — generated by SweetPad. Do not edit.
//
// Renders a specific #Preview inside the running app so SweetPad can stream it
// to VSCode. No third-party dependencies. One-time setup:
//
//   1. Add this file to your app target.
//   2. In your @main App, show SweetPadPreviewHost.rootView() when present:
//
//        @main struct MyApp: App {
//          var body: some Scene {
//            WindowGroup {
//              if let preview = SweetPadPreviewHost.rootView() { preview }
//              else { ContentView() }
//            }
//          }
//        }
//
//   3. Build & Run once on a simulator (SweetPad: Run), then use the
//      "Preview in VSCode" CodeLens or the SwiftUI Previews view.
//
// Discovery walks the Mach-O __swift5_proto section to find #Preview macros —
// adapted from EmergeTools/SnapshotPreviews (MIT). Requires Debug builds with
// dead-code stripping disabled so preview metadata stays in the binary.

#if DEBUG
import Foundation
import MachO
import SwiftUI
#if canImport(DeveloperToolsSupport)
import DeveloperToolsSupport
#endif

public enum SweetPadPreviewHost {
  /// The preview id requested by SweetPad, e.g. "Sources/Feature/ContentView.swift:10".
  public static var requestedPreviewId: String? {
    ProcessInfo.processInfo.environment["${ENV_PREVIEW_ID}"]
  }

  /// Optional appearance override ("light" / "dark").
  public static var appearance: ColorScheme? {
    switch ProcessInfo.processInfo.environment["${ENV_PREVIEW_APPEARANCE}"] {
    case "dark": return .dark
    case "light": return .light
    default: return nil
    }
  }

  /// The view for the requested preview, or nil when SweetPad didn't request
  /// one (so the app boots normally).
  @MainActor
  public static func rootView() -> AnyView? {
    guard let id = requestedPreviewId else { return nil }
    let view: any View = SweetPadPreviewBridge.view(forId: id)
      ?? SweetPadPreviewBridge.notFoundView(id: id)
    if let scheme = appearance {
      return AnyView(AnyView(view).preferredColorScheme(scheme))
    }
    return AnyView(view)
  }
}

// MARK: - Runtime preview discovery (vendored from EmergeTools/SnapshotPreviews, MIT)

enum SweetPadPreviewBridge {
  /// Find the #Preview macro whose recorded fileID/line matches the id and render it.
  @MainActor
  static func view(forId id: String) -> (any View)? {
    let target = parseId(id)
    if #available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, *) {
      for result in getPreviewTypes() where result.proto == "PreviewRegistry" {
        let metatype = unsafeBitCast(result.accessor(), to: Any.Type.self)
        guard let registry = metatype as? any PreviewRegistry.Type else { continue }
        guard registry.line == target.line else { continue }
        let fileID = registry.fileID
        guard fileID == target.file || fileID.hasSuffix("/" + target.file) else { continue }
        guard let preview = try? registry.makePreview(),
              let body = makeBodyChild(of: preview) else { return nil }
        return invokeMakeBody(body)
      }
    }
    return nil
  }

  static func notFoundView(id: String) -> any View {
    Text("SweetPad: no #Preview matched\n\(id)")
      .font(.footnote)
      .multilineTextAlignment(.center)
      .padding()
  }

  /// "Sources/Feature/ContentView.swift:10" -> (file: "ContentView.swift", line: 10).
  static func parseId(_ id: String) -> (file: String, line: Int) {
    let parts = id.split(separator: ":")
    let line = parts.count > 1 ? Int(parts[parts.count - 1]) ?? -1 : -1
    let path = parts.count > 1 ? parts[0 ..< (parts.count - 1)].joined(separator: ":") : id
    let file = path.split(separator: "/").last.map(String.init) ?? path
    return (file, line)
  }

  /// boxed is an Any wrapping the preview's @MainActor () -> any View closure
  /// (two words, stored inline in the existential buffer). Read it out and call
  /// it while boxed (which retains the closure's context) is alive. A sized
  /// load avoids the unsafeBitCast(Any, …) size-mismatch trap.
  @MainActor
  static func invokeMakeBody(_ boxed: Any) -> (any View)? {
    typealias Make = @MainActor () -> any View
    guard MemoryLayout<Make>.size <= MemoryLayout<Any>.size else { return nil }
    let make = withUnsafeBytes(of: boxed) { raw -> Make in
      raw.baseAddress!.assumingMemoryBound(to: Make.self).pointee
    }
    return make()
  }

  /// Reflect a DeveloperToolsSupport.Preview: source -> structure -> singlePreview -> makeBody.
  static func makeBodyChild(of preview: Any) -> Any? {
    func child(_ mirror: Mirror, _ label: String) -> Mirror? {
      mirror.children.first { $0.label == label }.map { Mirror(reflecting: $0.value) }
    }
    let root = Mirror(reflecting: preview)
    guard let source = child(root, "source"),
          let structure = child(source, "structure"),
          let single = child(structure, "singlePreview"),
          let makeBody = single.children.first(where: { $0.label == "makeBody" }) else {
      return nil
    }
    return makeBody.value
  }
}

// MARK: Swift ABI metadata + __swift5_proto walk

private struct SPBProtocolConformanceDescriptor {
  let protocolDescriptor: Int32
  var nominalTypeDescriptor: Int32
  let protocolWitnessTable: Int32
  let conformanceFlags: SPBConformanceFlags
}

private struct SPBProtocolDescriptor {
  let flags: UInt32
  let parent: Int32
  let name: Int32
  let numRequirementsInSignature: UInt32
  let numRequirements: UInt32
  let associatedTypeNames: Int32
}

private enum SPBContextDescriptorKind: UInt8 {
  case Module = 0
  case Extension = 1
  case Anonymous = 2
  case protocolType = 3
  case OpaqueType = 4
  case Class = 16
  case Struct = 17
  case Enum = 18
}

private struct SPBContextDescriptorFlags {
  private let rawFlags: UInt32
  var kind: SPBContextDescriptorKind? {
    SPBContextDescriptorKind(rawValue: UInt8(rawFlags & 0x1F))
  }
}

private struct SPBTargetModuleContextDescriptor {
  let flags: SPBContextDescriptorFlags
  let parent: Int32
  let name: Int32
  let accessFunction: Int32
}

private enum SPBTypeReferenceKind: UInt32 {
  case DirectTypeDescriptor = 0
  case IndirectTypeDescriptor = 1
  case DirectObjCClassName = 2
  case IndirectObjCClass = 3
}

private struct SPBConformanceFlags {
  private let rawFlags: UInt32
  var kind: SPBTypeReferenceKind? {
    SPBTypeReferenceKind(rawValue: (rawFlags & (0x7 << 3)) >> 3)
  }
}

private typealias SPBLookupResult = (name: String, accessor: () -> UInt64, proto: String)

private func spbGetTypeName(descriptor: UnsafePointer<SPBTargetModuleContextDescriptor>) -> String? {
  let flags = descriptor.pointee.flags
  var parentName: String? = nil
  if descriptor.pointee.parent != 0 {
    let parent = UnsafeRawPointer(descriptor)
      .advanced(by: MemoryLayout<SPBTargetModuleContextDescriptor>.offset(of: \.parent)!)
      .advanced(by: Int(descriptor.pointee.parent))
    if abs(descriptor.pointee.parent) % 2 == 1 { return nil }
    parentName = spbGetTypeName(descriptor: parent.assumingMemoryBound(to: SPBTargetModuleContextDescriptor.self))
  }
  switch flags.kind {
  case .Module, .Enum, .Struct, .Class:
    let name = UnsafeRawPointer(descriptor)
      .advanced(by: MemoryLayout<SPBTargetModuleContextDescriptor>.offset(of: \.name)!)
      .advanced(by: Int(descriptor.pointee.name))
      .assumingMemoryBound(to: CChar.self)
    let typeName = String(cString: name)
    if let parentName = parentName { return "\(parentName).\(typeName)" }
    return typeName
  default:
    return parentName
  }
}

private func spbParseConformance(_ conformance: UnsafePointer<SPBProtocolConformanceDescriptor>) -> SPBLookupResult? {
  let flags = conformance.pointee.conformanceFlags
  guard case .DirectTypeDescriptor = flags.kind else { return nil }
  guard conformance.pointee.protocolDescriptor % 2 == 1 else { return nil }
  let descriptorOffset = Int(conformance.pointee.protocolDescriptor & ~1)
  let jumpPtr = UnsafeRawPointer(conformance)
    .advanced(by: MemoryLayout<SPBProtocolConformanceDescriptor>.offset(of: \.protocolDescriptor)!)
    .advanced(by: descriptorOffset)
  let address = jumpPtr.load(as: UInt64.self)
  guard address != 0 else { return nil }
  let protoPtr = UnsafeRawPointer(bitPattern: UInt(address))!
  let proto = protoPtr.load(as: SPBProtocolDescriptor.self)
  let namePtr = protoPtr
    .advanced(by: MemoryLayout<SPBProtocolDescriptor>.offset(of: \.name)!)
    .advanced(by: Int(proto.name))
  let protocolName = String(cString: namePtr.assumingMemoryBound(to: CChar.self))
  guard ["PreviewProvider", "PreviewRegistry"].contains(protocolName) else { return nil }
  let typeDescriptorPointer = UnsafeRawPointer(conformance)
    .advanced(by: MemoryLayout<SPBProtocolConformanceDescriptor>.offset(of: \.nominalTypeDescriptor)!)
    .advanced(by: Int(conformance.pointee.nominalTypeDescriptor))
  let descriptor = typeDescriptorPointer.assumingMemoryBound(to: SPBTargetModuleContextDescriptor.self)
  guard let kind = descriptor.pointee.flags.kind,
        [SPBContextDescriptorKind.Class, .Struct, .Enum].contains(kind),
        let name = spbGetTypeName(descriptor: descriptor) else {
    return nil
  }
  let accessFunctionPointer = UnsafeRawPointer(descriptor)
    .advanced(by: MemoryLayout<SPBTargetModuleContextDescriptor>.offset(of: \.accessFunction)!)
    .advanced(by: Int(descriptor.pointee.accessFunction))
  let accessFunction = unsafeBitCast(accessFunctionPointer, to: (@convention(c) () -> UInt64).self)
  return (name, accessFunction, protocolName)
}

#if arch(i386) || arch(arm) || arch(arm64_32)
private typealias SPBMachHeader = mach_header
#else
private typealias SPBMachHeader = mach_header_64
#endif

private func getPreviewTypes() -> [SPBLookupResult] {
  var types = [SPBLookupResult]()
  for i in 0 ..< _dyld_image_count() {
    guard let header = _dyld_get_image_header(i) else { continue }
    let headerType = UnsafeRawPointer(header).assumingMemoryBound(to: SPBMachHeader.self)
    guard headerType.pointee.flags & MH_DYLIB_IN_CACHE == 0 else { continue }
    let imageName = String(cString: _dyld_get_image_name(i))
    guard !imageName.contains(".simruntime"),
          !imageName.contains(".platform"),
          !imageName.hasPrefix("/usr/lib/"),
          !imageName.hasPrefix("/System/Library/") else {
      continue
    }
    var size: UInt = 0
    let sectStart = UnsafeRawPointer(getsectiondata(headerType, "__TEXT", "__swift5_proto", &size))?
      .assumingMemoryBound(to: Int32.self)
    if var sectData = sectStart {
      for _ in 0 ..< Int(size) / MemoryLayout<Int32>.size {
        let conformance = UnsafeRawPointer(sectData)
          .advanced(by: Int(sectData.pointee))
          .assumingMemoryBound(to: SPBProtocolConformanceDescriptor.self)
        if let result = spbParseConformance(conformance) { types.append(result) }
        sectData = sectData.successor()
      }
    }
  }
  return types
}
#endif
`;
