// swift-tools-version: 6.0
// Generated by sweetpad (build generate --backend xtool). Edit as needed.
import PackageDescription

let package = Package(
    name: "SweetpadXtool",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "SweetpadXtool", targets: ["SweetpadXtool"]),
    ],
    targets: [
        .target(
            name: "SweetpadXtool",
            path: "Sources",
            sources: [
                "App.swift",
                "ContentView.swift",
                "Greeting.swift",
            ]
        ),
    ]
)
